/** 
*ASCII stands for : American Standard Code for Information Interchange.  
* is the most common character encoding format for text data in computers
* it solved many graphing problems
*/
println("                      ti");
println("                    fl1;*01tf;k      :.");
println("                    klajal,afsdkjsakjfas,,,");
println("                   ..$£^&*^hjhjdk<,,,,,sa,s");
println("         jhkdfhndfkjh^U*&IUIJHJKSd,,,.s.k");
println("       .s.,asdfm,&^^&(*UIKJJKHJHJjjjHkjhk");
println("       kasl(*UIjklhJjjjkfdjdjladkjflksjf.");
println("       jlksdjfkl(*P*()OIJ/djflksdfjlksdjfkd");
println("       kasjf..sd,fs.,,sdfklj2@@@@@*££(iwejkfkd");
println("       ldjfklsdf.,,,ad.f..dsf..djsdjf0w9eiofdj");
println("         kalsdjfkladjfklsdfosdf0q9woi111111111");
println("            klsadjfkjkadfjlskjfklasj111111111");
println("                askldjfkjldkfjkdlaso...,mx,.");
println("                 jkjklskdfjlksdjflksjdj,,,,,,");
println("               salkfjask   @@$,,,,&*,,...11111111                                   '-");
println("              akhjkhjkhj   jhkjo,,,,,kjhkj11111111111                             11,;");
println("              asik@!£$%^   hjhdj,,,,,,,hdhj11111111111111                      ,sdk;");
println("              .a&&&&&&&    asdkj,,,,,,,,,kasd1111111111111                 1wel;");
println("                 skjfl     lkadsl,,,,kdkfjsddfkj1111111111111gd            lfjs,");
println("                           dklasj,,,,,,jkdfjljdffkdjffj1111111111111         .asl;;ks");
println("                           klsdjf,,,,fkjsad;klfjsdaklfj,111111111kds        k;aakddd");
println("                           kkjdlk,,,,fxkjldkfj df[qpworldfj;kadf11111111111      osdklkjd");
println("                           jklfdl,,,,,dkfjdaaadljlkdjm s111111,1,1,11,*(IUhfhdjadfadslkja");
println("                           flaksdj,,,;ldfkjkljfkdlsjfldlkfjlk11111111111111111dkgjkldf");
println("                         sjdsflskfj,,,sdksdkfjsdjsdlkfjklf1111111111111111lkasfkls");
println("                       sdakfjaskdfj,,,lskadfjklasdfjslkd,,,,,11111111111slkfdl");
println("                       klsdjflksajf,,,klsadfjklasjdkfjkl.,,,,1111111111111kd");
println("                                sdklfjksdfjksdjfklsdfjklsdjfslkdfjsd");

println("                                     <<<><<<<<<l***************<<<<<<<<<<<<<<<<<<<<<<<<<<");
println("                                     ,,,,****>>l>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<");
println("                                     l*********************************************");
println("                                      **********************************************");
println("                                      **************************************    ***");
println("                                      **        **      **      **     **       ***  ");
println("                                      **        **      **       **     **      ***");  
println("                                      **        **      **      **     **      ***");
println("                                      **        **      **     **      **      ***");
println("                                      **       **      **        **    **      ***");
println("                                     **         **      **      **     **     ***");
println("                                      **        **      **      **     **     ***");
println("                                      **        **      **       **    **     ***");
println("                                     **         **      **       **     **    ***");
println("                                     **         **      **       **     **   ***");
println("                                     **         **      **       **     **   ***");
println("                                     **         **      **       **     **   ***");
println("                                     **         **       **       **    **  ***");
println("                                     **          **     **       **    **   ***");
println("                                     lllllllllllllllllllllllllllllllllllllllllll");
println("                                     lllllllllllllllllllllllllllllllllllllllllll");
println("                                       lllllllllllllll          lllllllll     lll");
println("                                     ll                                       ;;;");
println("                                     ll                                       ;;;");
println("                         ;;;;;;;; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;");
println("           llllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll");
println("             ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;");
println("           ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;");    
println("           ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;    ;;;");
println("           llllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll;   ;; ;;;");
println("           ;;;;            ,    '         '''      '''              lll      ;; ;;;");
println("           ;;;;            ,    '         '''                       lll    ;;   '''");
println("           ;;;;                           ;;;                       lll  ;;     ;;;");
println("           ;;;;                  ''       ;;;                       lll ;;      lll");
println("           ;;;;   .c ,,          .        ;;;            ,,         lll         ;;;");
println("           llll                           '''                       ;;;         lll");
println("           ;;;;                           ;;;                       '''         ;;; ");
println("           llll                ..         '''                       ;;;         lll");
println("           llll                           ;;;                    .  ,,,         ;;;");
println("           llll                           ;;;                       '''         lll");
println("           llll             ,..                                     ;;;          lll");
println("           llll               .,                                    '''          ;;;");
println("           ;;;;                                                     lll          lll");
println("           ;;;;                                                     lll          ;;;");
println("           llll                                                     ;;;");
println("           iiii                                                     iii");
println("                                                                    iii");
println("                                                                    ttt");
